# Generated by Django 5.1.4 on 2025-03-25 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='default-slug')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Croping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('optimal_temperature_min', models.FloatField()),
                ('optimal_temperature_max', models.FloatField()),
                ('optimal_humidity_min', models.FloatField()),
                ('optimal_humidity_max', models.FloatField()),
                ('optimal_soil_moisture_min', models.FloatField()),
                ('optimal_soil_moisture_max', models.FloatField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('specialty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('research_area', models.TextField(blank=True, null=True)),
                ('publications_count', models.PositiveIntegerField(default=0)),
                ('date_joined', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('equipment', 'Equipment'), ('seedling', 'Seedling'), ('other', 'Other')], default='other', help_text='Type of product: Equipment, Seedling, or Other', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty_period', models.IntegerField(blank=True, help_text='Warranty period in months (for equipment)', null=True)),
                ('seed_type', models.CharField(blank=True, help_text='Type of seedling (e.g., vegetable, fruit, grain)', max_length=100, null=True)),
                ('growth_duration', models.IntegerField(blank=True, help_text='Growth duration in days (for seedlings)', null=True)),
                ('available_quantity', models.IntegerField(help_text='Available quantity in stock')),
                ('description', models.TextField(blank=True, help_text='Additional details or product description', null=True)),
                ('location', models.CharField(help_text='Location of the product', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agricultural Product',
                'verbose_name_plural': 'Agricultural Products',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
